---
- name: Configure the IP on the Ansible Docker container
  gather_facts: false
  hosts: localhost
  vars:
    ip: "192.168.{{ lookup('env','VLAN') | default('1', true) }}.{{ lookup('env','HOST') | default('1', true) }}"
    gateway: "192.168.{{ lookup('env','VLAN') | default('1', true) }}.254"


  tasks:
    - name: Check If Configured
      shell: ip address show dev eth0
      register: ipconfig_check1

    - name: Configure IP
      shell: ip address add {{ ip }}/24 dev eth0
      when:
        - ip not in ipconfig_check1.stdout

    - name: Check IP Config
      shell: ip address show dev eth0
      register: ipconfig

    - name: Assert that IP is configured
      assert:
        that:
          - ip in ipconfig.stdout

    - name: Check Route Configured
      shell: ip route
      register: iproute_check1

    - name: Configure Gateway
      shell: ip route add default via {{ gateway }}
      when:
        - gateway not in iproute_check1.stdout

    - name: Check Routing configuration
      shell: ip route
      register: iproute

    - name: Assert that gateway is configured
      assert:
        that:
          - gateway in iproute.stdout
