---
- name: Configure the IP on the Ansible Docker container
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Check If Configured
      shell: ip address show dev eth0
      register: ipconfig_check1

    - name: Configure IP
      shell: ip address add 192.168.1.1/24 dev eth0
      when:
        - '"192.168.1.1" not in ipconfig_check1.stdout'

    - name: Check IP Config
      shell: ip address show dev eth0
      register: ipconfig

    - name: Assert that IP is configured
      assert:
        that:
          - '"192.168.1.1" in ipconfig.stdout'

    - name: Check Route Configured
      shell: ip route
      register: iproute_check1

    - name: Configure Gateway
      shell: ip route add default via 192.168.1.254
      when:
        - '"default via 192.168.1.254" not in iproute_check1.stdout'

    - name: Check Routing configuration
      shell: ip route
      register: iproute

    - name: Assert that gateway is configured
      assert:
        that:
          - '"default via 192.168.1.254" in iproute.stdout'
